### ISSUE TITLE
[BUG] Souls such as (as far as i have tested) dagger and spear, likely to be all of epic fight mod weapons, cannot have their specific weapon soul type applied to them.

### ISSUE THREAD

**Issue by AetherMemes** [mahjerion/Craft-to-Exile-2-Resolution#32] opened 2021-11-05 20:50 UTC
Its just that

**Comment by mahjerion** [comment] 2021-11-08 14:58
duplicate of #30

**Closed by mahjerion** 2021-11-08 14:58 UTC
Labels: bug
